# Generated by Django 4.2.18 on 2025-01-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_comment_comment_approved_comment_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.FloatField(default=3.5),
        ),
    ]
