# Generated by Django 4.2.18 on 2025-02-10 22:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featureed_image',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1629780000/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
