# Generated by Django 4.2.18 on 2025-02-10 22:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_featureed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featureed_image',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
